### PR TITLE
2701: make sure cookieBehavior is always honored

### PR DESCRIPTION
**Pull request by earthlng**
see https://github.com/ghacksuserjs/ghacks-user.js/issues/862

thanks @crssi !

### CODE REVIEW

**Comment by Thorin-Oakenpants** [comment]
I think we need to add some info

[NOTE] Enforcing category to custom ensures the cookie pref is honored due to a Firefox bug

**Comment by earthlng** [comment]
sure, why not.

```js
 * [NOTE] Enforcing category to custom ensures the cookie pref is always honored. see [x]
 * [x] https://bugzilla.mozilla.org/...
```

**Comment by Thorin-Oakenpants** [comment]
yup, we'll just add the bug number when it lands. go ahead and do that and commit

**Comment by Thorin-Oakenpants** [comment]
wait a sec

**Comment by Thorin-Oakenpants** [comment]
in my email: i said this

> Note: we have a workaround: which is to enforce the ETP category to custom (which doesn't hurt even if all ETP prefs are at default and technically it should be at standard)

I think this might be good to work in (just not that wordy) .. i.e the category pref at custom "can't hurt" regardless of what ETP config they have

**Comment by earthlng** [comment]
wait, you sent an email to your top-notch security/privacy contacts about this rather insignificant edge-case scenario?!? so now *they* have to open a bugzilla ticket? Don't you think they have better things to do than *that*? I mean it's not for me to decide but I think you're stretching it a bit here.

> pref at custom "can't hurt" 

I don't think that's necessary but whatever

**Comment by Thorin-Oakenpants** [comment]
Yes, I contacted via email for **them** to open
- I think it is more than an edge case: enterprise policies might be affected (if they have ETP), and enterprises using cfg (or whatever it is) will have this issue
- re enterprise: I've found Kaply to be a little dismissive at times (just my perception), so coming via tom might be better if he's involved (not that we don't have a workaround anyway)
- because you publicly asked me to open the ticket, I can't unless I create another account

> I don't think that's necessary but whatever

I can see people asking .. my prefs are at default but it still shows custom. Not a deal breaker. I'm going to bed.

If you want, add the following and commit. We'll add the bugzilla later if they create one
```
 * [NOTE] Enforcing category to custom ensures the cookie pref is always honored. see [1]
 * [1] https://bugzilla.mozilla.org/... (bug number to come)
```

**Pull request merged**
