### PR TITLE
#138

### PR DESCRIPTION
**Pull request by Thorin-Oakenpants**
These all seem kinda lame TBH

### CODE REVIEW

**Comment by earthlng** [comment]
> disable permissions manager from writing to disk (requires restart)
> [NOTE] This means any permission exceptions are session only

ok - thx Cpt. Obvious xD

**Comment by Thorin-Oakenpants** [comment]
Yeah I know. Maybe we should just dump this and close #138

**Comment by Thorin-Oakenpants** [comment]
How do you delete a PR?

**Comment by earthlng** [comment]
You can commit this if you want, I think it's fine. If you want to delete the PR I guess you close it and see if something shows up to delete it afterwards

**Pull request merged**
