### PR TITLE
network.IDN_show_punycode

### PR DESCRIPTION
**Pull request by earthlng**
my draft for `network.IDN_show_punycode`
added under 2600 but it would maybe also fit under 0800 (?)
the title and that one line are quite long, feel free to improve the wording etc.

### CODE REVIEW

**Comment by Atavic** [comment]
> added under 2600
seems the optimal location to me.

**Comment by earthlng** [comment]
pyllyukko has the following url included, is it too much if we add it too?
http://kb.mozillazine.org/Network.IDN_show_punycode

**Comment by Atavic** [comment]
Your choice is better! Also, I think that a russian/arabic/hebrew user always sees the URL in its own alphabet but I can't confirm (I have a latin system language).

**Comment by Roman-Nopantski** [comment]
@earthlng  If you're happy with my little modifications, merge the pull request and them commit to master

**Comment by earthlng** [comment]
thx Pants, much better with your mods

**Pull request merged**
