### PR TITLE
Allows `updater.sh` to work with Thunderbird profiles as well

### PR DESCRIPTION
**Pull request by HorlogeSkynet**
This PR is a cleaned up version of @atomGit's [first draft](https://github.com/HorlogeSkynet/thunderbird-user.js/issues/1#issue-448915371), back in May 2019.

See (and closes) HorlogeSkynet/thunderbird-user.js#1.

**EDIT 2020-03-24** : Some stuffs were missing yesterday, now it should be better. Bye :wave:

(partial) related issues :
* #646
* #753
* HorlogeSkynet/thunderbird-user.js#10

### CODE REVIEW

**Comment by Thorin-Oakenpants** [comment]
Thanks. This is not my file or area of expertise, and there are a few changes here, so we'd need to sort through those with @earthlng or @overdodactyl 

The first thing I will say is that I'm not interested in having a file in this repo point at someone else's files or another application: it smacks of endorsement and this repo has nothing to do with Thunderbird.

So after all the TB changes are removed, what's left? Some exit code and typo improvements?

**Comment by atomGit** [comment]
seems to be some confusion about this patch, so...

i didn't submit the patch

i made a couple of very slight changes to the updater.sh to get to work with t-bird and the @HorlogeSkynet user.js for t-bird for my own use, then i wondered whether the ghacks crew would want to adopt the changes since i didn't see the sense in maintaining 2 copies that are nearly identical, plus i'm simply not qualified - i think i discussed this with HorlogeSkynet after which he submitted the patch for me since i didn't know how (i think he also cleaned up my code a little?)

if you guys don't want to adopt the changes, i understand - no problem

**Comment by Thorin-Oakenpants** [comment]
I doubt anyone who could is going to review any improvements. AFAIK it's not broken

**Comment by HorlogeSkynet** [comment]
Hi, thanks for your feedback.

IMHO, and concisely :

* The main rational behind this PR is, as projects share many common points, to drastically reduce the maintenance cost, and focus on the content. The proposed patch actually adds a new feature to the project "meta-environment", is fully backward-compatible for everyone.

* The main differences with CHEF-KOCH's TBCK (quickly denigrated in #646) is a proper documentation (mainly coming from _here_ btw) and would be the GHacks' updating script (at least) for Linux, working out-of-the-box, and honoring the same "standards" you were talking about [here](https://github.com/ghacksuserjs/ghacks-user.js/issues/646#issuecomment-473945511).

* Such a feature has been greatly discussed (see links above) and is expected from (at least a part of) the community (I would invite Daniel @dngray, @zdat from HorlogeSkynet/thunderbird-user.js#10, @claustromaniac & @ema-pe from [here](https://github.com/ghacksuserjs/ghacks-user.js/issues/646#issuecomment-496693653) and at least @aesthicc from... _here_, to join us discussing this).

* As you stated [here](https://github.com/ghacksuserjs/ghacks-user.js/issues/646#issuecomment-466202626) : `[...] I think it's a small project, but a worthy one - and I'd use it as well`, I agree and now you also got "community" members handling working on what you didn't/don't have to the time for. Look how fortunate you are ! You _only_ have to let the opportunity to make it easily usable to people already using it for FF.

So, would you consider re-opening this, and having a proper discussion with the "community"/the parties involved (and yes, I'd be pleased to get a proper review from @earthlng) ?

If you're really embarrassed with an "external" link, we could add one more `Are you sure you wanna fetch content from third ${USERJS_URL} URL ? [y/N]` validation step when `-t` is specified.

Bye :wave:

**Comment by ema-pe** [comment]
My 2 cents:

1. Sincerely I'm not interested on Thunderbird support. This repository is only for Firefox. If you want to add support for Thunderbird, it is better to merge the two projects.
2. The typos and error code fix seems good to me. It would be useful to check the script with [ShellCheck](https://www.shellcheck.net/) to find other minor issues (maybe with GitHub Actions this can be automatized).
3. I don't think is necessary to add new functionalities to the installer script. Remember that it is written in Bash and it can easily degenerate to a barely maintainable script.

**Pull request closed without merging**
