### PR TITLE
Updater.sh rework 2

### PR DESCRIPTION
**Pull request by h88e22dgpeps56sg**
##### DOWNLOAD_METHOD
* merge two declarations of download command into one
* add max-redirects to prevent redirect loops
* add silent options (prettier than `> /dev/null`)
##### download_file()
* shorten `download_file ()`
* exit instead of continue with a "non-file", which can lead to unwanted behavior
##### open_file()
* open_file(): pipe instead of nested sub-shell
##### readIniFile()
* readIniFile(): `grep -c` equals `grep | wc -l`
* make output prettier
* work with variable instead of temporary file
* update `PROFILE_PATH` more directly

### CODE REVIEW

**Comment by h88e22dgpeps56sg** [comment]
Sorry, I got a little carried away. Next time, I will split it into more commits.

**Comment by earthlng** [comment]
Hi again,

I like most of it but am not too keen on changing readIniFile() so radically. Also looks like `profpath` is undefined.

re: `open_file()` - are you sure `cut` is always available on all Nixes **and** all Mac's ??

**Comment by h88e22dgpeps56sg** [comment]
I could split the `download_file` stuff into 2 or more PRs, so it is not too much at once.

Fixed `profpath`.

Yes, `cut` is a POSIX command and therefore included in every *nix OS and MacOS is unix based, too:
[Wikipedia](https://en.wikipedia.org/wiki/List_of_Unix_commands) says: cut – Mandatory
[An A-Z Index of the Apple macOS command line (macOS bash)](https://ss64.com/osx/) lists: cut

**Comment by earthlng** [comment]
Ok, thanks for the info about `cut`. `download_file` is not the issue, it's readIniFile(). I spent quite some time writing and testing that function and I don't have the time or willingness to redo that at the moment. If you have more changes you want to make, let's keep the readIniFile() mods for last so that I can look at it when I have some time and you don't have to wait that long for more PR's.
The only problem I see with the new `download_file` is that if we end up exiting at `download_file` in `update_userjs` we don't restore the original working directory.

ps there's also a leftover `legacy_lc` [line](https://github.com/ghacksuserjs/ghacks-user.js/blob/master/updater.sh#L336) that we can remove

**Comment by h88e22dgpeps56sg** [comment]
Sorry, my initial comment had `download_file()` but I edited it to `readIniFile()`.

* reverted `readIniFile()` back to normal.
* removed leftover line
* changed the exits to returns, so that the updater will cd back at the end
* added error message in case of a download failure (that was a little tricky in combination with `declare -r`)

**Comment by earthlng** [comment]
Thanks mate. 
- How about we return empty string (`echo ''`) and check `newfile` directly so we don't need `ret`? That's cleaner IMO.
- ideally add a similar check to the other 2 places where we call download_file()
- There's an old typo/bug that I forgot to fix the last time: [FSAVEIFS](https://github.com/ghacksuserjs/ghacks-user.js/blob/master/updater.sh#L241) vs [SAVEIFS](https://github.com/ghacksuserjs/ghacks-user.js/blob/master/updater.sh#L248)
- if you want, add yourself to the [list of contributors](https://github.com/ghacksuserjs/ghacks-user.js/blob/master/updater.sh#L7)
- with all that in place, we can rollout a new version so please increase the version number

**Comment by h88e22dgpeps56sg** [comment]
All done. :)

**Comment by earthlng** [comment]
Perfect! Thank you

**Pull request merged**
