### PR TITLE
Update user.js

### PR DESCRIPTION
**Pull request by earthlng**
things not in the PR:

- 0911 - remove? or replace with `network.auth.subresource-http-auth-allow` (would need to add it to troubleshooter as well)
- 1022 - does it even do what we expect it to do? remove?
- 1700 - SETUP-CHROME and maybe add a recommendation for TC?
- 2002 - add test page?
- 2302 - [FF32+] - added in 32, enabled in 44 (still disabled in ESR60!)

### CODE REVIEW

**Comment by earthlng** [comment]
just a couple things I'd like to change ...

:jeans:, :cat2:

**Comment by Thorin-Oakenpants** [comment]
see https://github.com/ghacksuserjs/ghacks-user.js/issues/575 OP .. 1022 = inactive or remove (I'm fine with removing it)

**Comment by earthlng** [comment]
the only reason why it could make sense to disable it IMO (assuming it even does disable session restore after crash!) would be if a tab manages to take down the whole browser you probably don't want to restore that tab

**Comment by Thorin-Oakenpants** [comment]
1260: that's web breakage - if sha-1 is restricted, pages won't load .. web breaks. Just like not allowing DRM breaks video, video will not load. I know we can argue semantics here.

`user_pref("devtools.webide.adaptersAddonURL", "");` - why add a deprecated in FF57 pref? I don't mind, just wondering why. And is that in the `[-]` reference link?

The rest looks fine on first glance. I still need to go thru [SETUP* and make sure we have things in the right places. end of 1st line if ok, but in body if the next comment specifically is about that. So yeah, those moves look ok as well

**Comment by earthlng** [comment]
> Useful if repeated crashes on restore are caused by a malicious tab

that implies that it does what we *think* it does. You're the one with the scratchpad to crash FF ... :)

**Comment by Thorin-Oakenpants** [comment]
> 1700 - SETUP-CHROME and maybe add a recommendation for TC

No need to add setup tag (and I am going to get those all out of headers). Recommendation for TC, IDK - it hasn't really been updated for like 6 months from memory - mostly lint and things. The issues are piling up.

**Comment by Thorin-Oakenpants** [comment]
Can I do a little editing to undo a couple of things and push this thru. I'd like to address the others one by one - i think my comment about not wanting make a note/todo list before was ambiguous. I meant for a single change it wasn't worth opening an issue.

**Comment by earthlng** [comment]
> If 1260 causes a problem, what does the end user experience?

AFAIK that pref alone does nothing if you don't also set a proxy, fe fiddler. So most people will never have a problem with that pref and people who use fiddler or similar should have no problem knowing where to look to make it work. (1200 = HTTPS, CERTS, etc)
IMO we can just drop that tag all together so we don't have to argue WEB vs CHROME :)

**Comment by earthlng** [comment]
> Can I do a little editing to undo a couple of things and push this thru

sure

**Comment by earthlng** [comment]
> re: 1700 - "No need to add setup tag"

I mean currently due to needing to long-press to even have the option to use containers show up on `+`, some (most?) people won't even notice that we enabled containers. That's why I think it needs a setup tag of some kind.

**Comment by earthlng** [comment]
I'll update the deprecated sticky

**Comment by Thorin-Oakenpants** [comment]
> I mean currently due to needing to long-press to even have the option to use containers show up on +, some (most?) people won't even notice that we enabled containers. That's why I think it needs a setup tag of some kind.

Oh, i get ya. We can add one to the long press pref if you want. As for noticing it's on - users might notice them in right click contexts, and it will show in options as well. That should suffice

**Comment by earthlng** [comment]
maybe change
`1704: set long press behaviour on "+ Tab" button to display container menu`
to
`1704: set behaviour on "+ Tab" button to display container menu`
and `2=the menu is shown on long press` ?

**Comment by earthlng** [comment]
`0=no menu (default), 1=show when clicked, 2=show on long press`
and
`[NOTE] The menu does not contain a non-container tab option (use Ctrl+T to open non-container tab)`

**Comment by claustromaniac** [comment]
- 0911 - remove? or replace with... :cat2:: replace!  (with `user_pref("network.auth.subresource-http-auth-allow", 0);` or `1`? I'd go with `0`, but IDK I'M NEW AT THIS SHIT!!! :scream_cat: \*freaking out\*).

> Recommendation for TC, IDK - it hasn't really been updated for like 6 months from memory - mostly lint and things. The issues are piling up.

who cares about a bunch of minor issues and feature requests not getting solved as long as the shit works? especially when we talk about such a useful extension! My own shitty extensions are heading the same way, except they're not nearly as useful!!! :sweat_smile:  It is already recommended on the wiki though, so it doesn't matter anyway.

**Comment by Thorin-Oakenpants** [comment]
[NOTE] kinda lends weight (while our active value is the best so as to not spring nasty surprises - if FF ever flip containers on, I bet they go for 2 as well). I like that we added a setup tag to draw attention to it (the setting as well as the fact we turned containers on). The other prefs make no difference.

And, I want to get [setup tags against prefs. They don;t work with the real-time thingy if they are stuck in section headers. That doesn't mean we can't *also* have them in headers, but it creates duplicity. At the end of the day, I want users in the js and on the whizzy-do dactyl site, to be able to jump from pref to pref and make changes or troubleshoot. The less in section headers the better

**Comment by Thorin-Oakenpants** [comment]
OK, I need to DL a copy and compare with my local master, then I'll start a new issue, or commandeer one, and add in all the things we haven't addressed from here

**Comment by earthlng** [comment]
re: 0911

`pref("network.auth.subresource-img-cross-origin-http-auth-allow", true);` only prevents IMAGES from triggering a login prompt.
It was added in FF55 and is default false since FF59 = no need to enforce it anymore. We probably added it before it was set to false

`pref("network.auth.subresource-http-auth-allow", 2);` was added in FF41 and supports the following values:
```js
// Sub-resources HTTP-authentication:
//   0 - don't allow sub-resources to open HTTP authentication credentials dialogs
//   1 - allow sub-resources to open HTTP authentication credentials dialogs,
//       but don't allow it for cross-origin sub-resources
//   2 - allow the cross-origin authentication as well.
```

AFAIK HTTP Auth is pretty rare nowadays and 0 should probably be fine. 1 = less breakage

**Comment by Thorin-Oakenpants** [comment]
> who cares about a bunch of minor issues and feature requests

Yeah I'm fine with it being recommended. Was just querying its status (I don't use it). From the outside looking in, I was just querying it's status. For all I know, it's stable AF. I'll defer to you and :earth_americas: since you gals use it. It's on the task list FYI

**Pull request merged**
