### PR TITLE
Update updater.sh

### PR DESCRIPTION
**Pull request by claustromaniac**

### CODE REVIEW

**Comment by earthlng** [comment]
is it important enough to increase the version number?

**Comment by claustromaniac** [comment]
> is it important enough to increase the version number?

IDK, is it? I wasn't sure myself that's why I didn't touch it.

**Comment by earthlng** [comment]
when in doubt just do it :) let's go with a new version

**Comment by earthlng** [comment]
you can merge it yourself but please always use "Squash and merge". Thanks

**Pull request merged**
