### PR TITLE
Standardize Part2 #115

### PR DESCRIPTION
**Pull request by Thorin-Oakenpants**

### CODE REVIEW

**Comment by earthlng** [comment]
2604: why [MAC]? see [OS-diff](https://earthlng.github.io/FFprefs-diffs/Firefox-v53.0.html) - also exists in Win+Linux
2605: why [WINDOWS]? it's not in the OS diff
2669: strip is the correct word to use and is not the same as remove

**Comment by Thorin-Oakenpants** [comment]
2604 read the ticket (I actually read about 7 of these damn things, most to do with thunderbird) - it is on Mac that a temp file is created and not removed, on the desktop (maybe @grauenwolfe can help) - the pref is only useful in Mac as far as i can tell

2605 - ohh, then if this applies to Mac and Linux then the wording of the pref is fuked

2669: "remove paths" is the same as "strip paths" especially to a layman. Yes strip is better, but some compromises have to be made. I'll think about it.

**Comment by Thorin-Oakenpants** [comment]
2604: browser.helperApps.deleteTempFileOnExit - default in windows/linux is true - but on a MAC is false, but I'll remove the tag

2605: http://kb.mozillazine.org/Browser.download.manager.addToRecentDocs - I know this is old, but it says WINDOWS only. That page says it four times. But I will look further .. https://www.lifewire.com/modifying-download-settings-in-firefox-445716  .. says windows only ...  https://dxr.mozilla.org/mozilla-central/source/toolkit/components/jsdownloads/src/DownloadPlatform.cpp#110

>// On Windows and Gtk, add the download to the system's "recent documents" list, with a pref to disable.

So it's [WINDOWS] [ANDROID] then?

**Comment by earthlng** [comment]
disable integration of activity into ~~windows~~ system's recent documents
or:
disable adding downloads to the system's "recent documents" list (to use the same words as mozilla)

Idk if GTK is Android too but it's definitely used in (some?) Linux and since MAC is based on Linux maybe there too. I think we could remove the OS tags. Everyone will know if their system has "recent documents" or not

**Pull request merged**
