### PR TITLE
font visibility / RFP

### PR DESCRIPTION
**Pull request by Thorin-Oakenpants**

### CODE REVIEW

**Comment by Thorin-Oakenpants** [comment]
We should also add something to `1401` about how the whitelist is **currently** limited in FF80+ by RFP/font-vis

**Comment by earthlng** [comment]
better link for [1] in 4618: https://searchfox.org/mozilla-central/search?path=StandardFonts*.inc

**Comment by Thorin-Oakenpants** [comment]
merge if you're happy

**Comment by Thorin-Oakenpants** [comment]
actually, technically bundled fonts are included, so we should say

**Comment by Thorin-Oakenpants** [comment]
@earthlng I'm done ... merge if you're happy

**Comment by crssi** [comment]
Does RFP set as `true` act as `layout.css.font-visibility.level` =`1`?

**Comment by Thorin-Oakenpants** [comment]
^^ that's what it says .. FF80+

**Comment by crssi** [comment]
I am obviously blind again. 😢 

Where it says FF80+? I can see only FF79+ https://github.com/ghacksuserjs/ghacks-user.js/blob/c4b7e076911e8f674ccdeaa9e3747340baf39c87/user.js#L1610-L1615

**Comment by Thorin-Oakenpants** [comment]
https://github.com/ghacksuserjs/ghacks-user.js/commit/2809854802b3756c26aa089987761f1bbd3f34ce#diff-b00df6cb4137c00991376cd319d35348R1465

**Comment by crssi** [comment]
Aaaaa... Thank you 😄 ❤️

**Pull request merged**
