### PR TITLE
remove [SETTING-ESR52] lines

### PR DESCRIPTION
**Pull request by earthlng**

### CODE REVIEW

**Comment by Thorin-Oakenpants** [comment]
Well fuck. Did a release, but totally forgot to change the version number and date before I did it. https://help.github.com/articles/editing-and-deleting-releases/ - I could not delete the release, it only seemed to wipe all the descriptions and left me with no edit anymore. Then I did the commit to change date+version and redid the 61 release, and it now tells me it has 1 commit to master since - but that commit was done *before* this release. And if I download the release (zip), sure enough it has the old date etc.

So now what?

**Comment by Thorin-Oakenpants** [comment]
I just edited the description - https://github.com/ghacksuserjs/ghacks-user.js/releases/tag/61.0

Kinda pisses me off, any attempt to recreate a v61 goes back to that point in time

**Comment by Thorin-Oakenpants** [comment]
@earthlng ^^ or I could delete it again (not sure if it really is deleted or it remains with no description - its weird) and create a 61.0.1? Either way it's a shitty outcome

**Comment by Thorin-Oakenpants** [comment]
https://help.github.com/articles/about-releases/
> Tags mark a specific point in the history of your project

So I guess that's that then. If I want a nice release with the fixed date + version, I would have to use a different tag

**Comment by earthlng** [comment]
it's just a date - who cares?! if you want to do a 61.0.1 that's fine too, I don't really care

**Comment by claustromaniac** [comment]
:jeans: , I played around with those features (tags/releases) a couple of weeks ago for the first time, and deleting seemed kind of weird at first for me, too (_maybe_ that has something to do with the fact that I didn't RTFM). I remember having seen something similar to what you describe, but I could successfully delete the whole tag from GitHub without using Git after a few tries. Moreover, I just tried the same again and I could do it without any problems.

After deleting the tag, you should indeed be able to re-create it pointing to another time in history (like that specific commit when you changed the date & version lines. Don't give up on me, :jeans:!! I would love to push the fixed tags myself, if I could, but I think Github doesn't have that functionality, and to push them from Git I'd need write access to this repo (and if I had write access I wouldn't need Git anyway) :disappointed:

Just go crazy on that tag 'til it gives up or something. (?) I mean, I would give you instructions on how to do it, but there really isn't much more to it than what the GitHub help page says. Once it's done, when you're going to re-create the tag you just change the Target to the hash of your desired commit (c4d131a ?), and presto.

**Comment by Thorin-Oakenpants** [comment]
On a good note, the release is authored by earthlng (cuz he played with it), and the note on the release implies that **he** fucked up, and not me :+1:

**Comment by claustromaniac** [comment]
I forked this repo in bare form, preserving all tags (using Git), and then I deleted that release + the 61.0 tag and re-created them pointing to b3b3ae4 (which is where you changed the date + version).

https://github.com/claustromaniac/ghacks-user.js/releases/tag/61.0

It's _not_ too late. But I don't really care, I just wanted to let you know that it still _is_ doable. You just have to delete the release first and then the tag. Is there any reason to not do it? Honest question, I really don't know.

**Comment by earthlng** [comment]
I'll give it a shot ...

**Comment by earthlng** [comment]
Done! Thanks mate, you're a true wizard :)

**Comment by earthlng** [comment]
seems to have worked: https://github.com/ghacksuserjs/ghacks-user.js/compare/61.0...master

... except [it doesn't say](https://github.com/ghacksuserjs/ghacks-user.js/releases) "x commits to master since this release" but maybe it'll update with the next commit

**Comment by claustromaniac** [comment]
> you're a true wizard

Nah, I just tamper and tinker, and then I pretend to know my shit by heart... but shh.. don't tell anyone. ;)

I tried adding a commit in my fork to see if that fixed the "x commits to master" thing, but it apparently didn't. Maybe adding another tag will fix it? Lets try that...

**Comment by claustromaniac** [comment]
Just FYI, the missing "x commits to master" thing was reported a few months ago. It seems to be either a bug or something they only partially removed from the platform.

https://github.community/t5/How-to-use-Git-and-GitHub/x-commits-to-master-since-this-release-is-missing/m-p/3705

**Pull request merged**
