### PR TITLE
Updater for Windows 3.1

### PR DESCRIPTION
**Pull request by claustromaniac**
Just some more polishing and some changes to prevent some potential issues when the user closes the console window too soon.

I still need @earthlng to test this because the `-updatebatch` switch didn't work for him before and it may be so again.

### CODE REVIEW

**Comment by earthlng** [comment]
> do you think I should still rename the scripts to .old or something before overwriting/deleting?

Yes. And I think adding the "how it works" you wrote [here](https://github.com/ghacksuserjs/ghacks-user.js/pull/298/commits/00e17281dc439c1e517671eeeb5bfc4e96f90104) at the top of the `IF DEFINED _updateb (` block would help a lot with understanding that part of the code.
---
instead of this:
```
IF EXIST user.js.old.bak ( DEL /F user.js.old.bak )
IF EXIST user.js (
	IF EXIST user.js.bak ( REN user.js.bak user.js.old.bak )
```
how about this? :
```
IF EXIST user.js (
	IF EXIST user.js.bak ( MOVE /Y user.js.bak user.js.old.bak )
```

---
re: carets - this
```js
user_pref("caret.x3x3", "!! ^^^true^^^");
```
gets merged to this:
```js
user_pref("caret.x3x3", " ^true^");
```

**Comment by Thorin-Oakenpants** [comment]
@earthlng Is it worthwhile adding a version/update date to both files

**Comment by earthlng** [comment]
only the version is enough

**Comment by claustromaniac** [comment]
> how about this? : 

The user could have bak files and no user.js file.

Regarding carets, I didn't test exhaustively but it only happens when exclamation marks are also involved, right?

**Comment by earthlng** [comment]
> The user could have bak files and no user.js file.

exactly, and you're deleting it even if there's no need to.

> it only happens when exclamation marks are also involved, right?

yes, but theoretically a pref that requires such a value could exist and at least nobody can blame us for not mentioning that merging could mess with that.

**Comment by claustromaniac** [comment]
> exactly, and you're deleting it even if there's no need to.

The script is never meant to leave a .bak.old backup file behind. If it did, the most likely reason is that the user closed it too soon. Deleting that file in that situation means doing what it would've done before.

> yes, but theoretically a pref that requires such a value could exist and at least nobody can blame us for not mentioning that merging could mess with that.

The point is that exclamation marks are still the real cause for issues, not carets.

**Comment by earthlng** [comment]
1. Oh okay, good point. Let's keep it as it is then.
2. that's true. Ok, I'll remove it from the howto.

**Comment by claustromaniac** [comment]
1. On second thought, the script will still delete that file later on in the code, and it will compare the files first, so it would be handled better that way. I will adopt the change you suggested.

**Comment by earthlng** [comment]
Lol, was just about to merge this but if you think it's better this way I'll take it. Anything else before I merge your 3rd non-rejected PR?? :)
The "**THe** normal flow here" maybe? last chance xD

**Comment by earthlng** [comment]
> New changes since you last viewed
> 3.1 ccaf069
> New changes since you last viewed
> Revert "3.1" a6c93b3 

looool what is happening?

**Comment by claustromaniac** [comment]
There you go. lol

**Comment by earthlng** [comment]
taking it in 3 ... 2 ... 1 ... Speak Now or Forever Hold Your Peace ... 0.9 .... 0.8 ....

**Comment by earthlng** [comment]
3 out of 5 - congrats! but more importantly - THANKS! good stuff

**Pull request merged**
