### PR TITLE
updater_overhaul

### LINKED ISSUE #537: bash script
Hi, I have a question about your script. 
https://github.com/ghacksuserjs/ghacks-user.js/blob/master/updater.sh

There are 2 mentions of two packages, wget and curl. These are packages that load something (in our case, user.js).
In this script, they are selected to choose from, because there is an "if" condition. The first package is "curl", but if it is not available (not installed or broken?), Then "wget" comes into play. However, what if there are none. ALL. NOT What then? second "if" is not there?
_this is not about debian distributions (for which they are available by default), but about (say) archlinux._
_On it, as far as I remember, you need to manually install it (although I could be wrong, I did not use it for a long time)._

and so it is possible to supplement the conditions on the verification (presence or absence) of these packages? Is there a guru js here?

I am not a guru in js, and maybe I’ll repeat myself I don’t understand. Explain to me?

_I hope I wrote without errors_ :cry:

### PR DESCRIPTION
**Pull request by overdodactyl**
In large part a restructuring/re-write of the last version.

* Uses `perl` as a last resort if `curl` and `wget`  are not available (fixes #537)
* Aborts and notifies user if none of the above are installed 
* Better use of functions
* When version numbers are checked, the contents are immediately saved to a temp dir.  This allows us to skip using wget/curl/perl a second time
* Improved messages for users
* Added various font colors for ease of use and aesthetics

Pinging @claustromaniac and @earthlng ... any feedback/opinions would be great!

### CODE REVIEW

**Comment by bogachenko** [comment]
it's awesome

**Comment by bogachenko** [comment]
it's awesome

**Comment by earthlng** [comment]
wow it looks great, both visually and code-wise.
Please review my commit and let me know if it makes sense and if you're happy with it.

I think you should also move `mkdir -p userjs_backups` into `backup_file()` because currently when the folder doesn't exist and `update_updater()` calls `backup_file()` the move command will probably fail (right?)

**Comment by overdodactyl** [comment]
Commit looks great, thanks! I moved the location of `mkdir -p userjs_backups` and made a few more changes, but nothing that should impact functionality.

**Comment by earthlng** [comment]
okay then, ready to merge. Thanks @overdodactyl

**Comment by claustromaniac** [comment]
Snazinessssssssssssssssssss!

I second bogachenko: this is awesome. Way more elegant than anything I'd usually write TBH :laughing:

**Comment by Thorin-Oakenpants** [comment]
> Screenshot of new printing:

Pants Romance :kiss: you know what I'm talking about

**Pull request merged**
