### PR TITLE
Updater for Windows v4.3

### PR DESCRIPTION
**Pull request by claustromaniac**
>  I'm being quoted to introduce something,
>  but I have no idea what it is and certainly
>  don't endorse it.	— [Randall Munroe](https://xkcd.com/1942/)

(sorry, I couldn't help myself)

I believe I gave you folks a decent enough rest from my incessant pull requests, so here I come again.

Just think that the more I bother you now, the less I'll bother you in the future. I mean, if these scripts someday become sentient beings capable of maintaining themselves, and if they are willing to, that will most likely be the last time you'll see me around.

Yes, @earthlng. I know I can't make sentient batch files. It was a joke this time.

### Changes:
- The script doesn't touch the `user.js` file until it really has to.
- The merge function is a bit smarter parsing files, at no significant cost. See examples below.
- Fixed a minor issue with the version check.
- Minor syntactic changes here and there.
### Additions:
- ~~New `-multiBackups` argument. I personally intend to use it to compare files and quickly review changes.~~ Ditched for -singleBackup argument.

<details> <summary> Merge function examples (click to expand) </summary><p>

**user.js contains:**
```
user_pref("first", "aaaaa");
user_pref("second", "aaaaa");
```
**user-overrides.js contains:**
```
user_pref(	"first"  , "bbbbb");
user_pref(	"first"  , "ccccc");
user_pref('first', 'ddddd');
user_pref('first', 'eeeee');
user_pref("second",
 "bbbbb");
user_pref("second", "ccccc");
user_pref("third",
 "aaaaa");
user_pref("third", "bbbbb");
```
**Result without these changes:**
```
user_pref("first", "aaaaa");
user_pref("second", "ccccc");
user_pref(	"first"  , "ccccc");
user_pref('first', 'eeeee');
 "bbbbb");
user_pref("third", "bbbbb");
 "aaaaa");
```
**Result with these changes:**
```
user_pref("first", 'eeeee');
user_pref("second", "ccccc");
user_pref("second",
 "bbbbb");
user_pref("third",
 "aaaaa");
user_pref("third", "bbbbb");
```
</p></details>

> 

P.S.: Forgive the copy-pasted commit description. I should've edited it at the very least. Oh well.. whatevs.

### CODE REVIEW

**Comment by earthlng** [comment]
Hi! meow meow. No idea who Earthing is but I'm sure (s)he appreciates being summoned to witness this :)

oh boy, lots of changes again. Will probably take a while until I have time to look at this in detail.
Any reason why we should keep singlebackup? I would prefer multibackup as the default, maybe with an optional -singlebackup.

**Comment by claustromaniac** [comment]
> No idea who Earthing is but I'm sure (s)he appreciates being summoned to witness this :)

In spite of my best efforts Github kept insisting on changing it to capital E, and I just gave up on it. I won't even try to correct it now lol.

> Will probably take a while until I have time to look at this in detail.

Take your time. I may have to make more changes soon anyway, depending on the outcome of #338. Besides, I'm not 100% convinced about the changes to the merge function. I want to try a few more things.

> Any reason why we should keep singlebackup? I would prefer multibackup as the default, maybe with an optional -singlebackup.

From the moment I added the `-updatebatch` switch I tried to keep changes to the default behaviour to a minimum so as to avoid giving someone an ugly surprise. When I wrote the first versions of the script I thought it was safe enough, so multiple backups wouldn't be necessary, but then in practice I found they would be **useful**. 

So, I wouldn't remove single backups because some people may prefer them, but turning them into an optional feature should be fine, I guess.

**Comment by earthlng** [comment]
Looks good and seems to work from what I can tell. But what are these `^M` on line 215 + 225?

**Comment by claustromaniac** [comment]
Pretty sure that's Github's syntax validation. Both lines contain double quotes but don't end in double quotes, it may have to do with that.

**Comment by earthlng** [comment]
merged. thanks

**Pull request merged**
