### PR TITLE
remove 0307: themes #648

### PR DESCRIPTION
**Pull request by Thorin-Oakenpants**
since 57(?) themes and web extensions are controlled by the same mechanism (301b+302b)

### CODE REVIEW

**Comment by earthlng** [comment]
It's a bit weird because when both 301b+302b are set to false then the UI setting `Update Add-ons Automatically` is unchecked (as expected). When you toggle the UI to enable, it sets both to true but when you uncheck it again, it only sets 0302b to false.
There doesn't seem to be a way to set 0301b to false via the UI other than about:config.

Some people might want to have extension updates enabled but themes updates disabled and I don't like to remove prefs that still do something and which to some extend keep FF a bit quieter.

**Comment by Thorin-Oakenpants** [comment]
> It's a bit weird because

Yeah I just commented in the issue about that. The [setting] for 0301b should go

**Comment by Thorin-Oakenpants** [comment]
> Some people might want to have extension updates enabled but themes updates disabled and I don't like to remove prefs that still do something and which to some extend keep FF a bit quieter.

The permutations are doing my head in a little. Need coffee. I tested the update with this pref at false, and it did not stop me **manually** checking (doh!) or updating.

The question is, if extensions update master switch is allowed, but themes isn't, what happens? I can try to test for it, but not if it takes a day

**Comment by earthlng** [comment]
> if extensions update master switch is allowed, but themes isn't, what happens?

it'll look for extension updates but not theme updates

**Comment by Thorin-Oakenpants** [comment]
^^ https://github.com/ghacksuserjs/ghacks-user.js/issues/648#issuecomment-463187686

**Comment by earthlng** [comment]
`extensions.update.enabled` is the master switch for the extension and theme update checks (+install in some cases) during the daily background update check. You can't disable the daily background checks entirely but you can make it not really do anything (other than update the timestamps).

if `extensions.update.enabled` is true, it will first do the LWT checks which are controlled by the pref you want to remove here. There doesn't seem to be a pref to just disable the auto-installing of LWTs, meaning that pref controls both LWT checking as well as installing. Or in other words LWT updates don't care about `extensions.update.autoUpdateDefault` - that's apparently just for extensions. (unless I'm missing something in the code)
Next it will go on to check extensions (and install them automatically depending on .autoUpdateDefault and/or each extensions individual auto-install setting)

And lastly the daily bg-check will also look for system addon updates but that's controlled in its own way and is besides the point here. The SA part is NOT affected by `extensions.update.enabled`!

**Comment by Thorin-Oakenpants** [comment]
So there must be a difference between a manual check and the one run internally by Firefox - I would have thought the code (spaghettified over the years?) would have been "reused".

I'm going to test this then: steps:
- `extensions.update.enabled` = true
- `extensions.update.autoUpdateDefault` = true (so I know the background update fired)
- `lightweightThemes.update.enabled` = false
- install 1 ext, 1 theme, both outdated versions
- open the test profile in 24+ hours

I'll get back to you. Regardless of the outcome (not doubting your code-reading skills), the pref will have to be modified (e.g only used in background checks), and most of the other changes still need to stand in some way or another

I actual decided to install a theme - it's almost identical to dark theme, but gets rid of the transparency in the title bar when the app loses focus. I had trouble with that in userChrome. And of course I have a coupel of other tweaks.

Thanks for looking into it

**Comment by Thorin-Oakenpants** [comment]
^^ and extensions.update.interval = 3600 (1hr, instead of 24 hrs)

**Comment by Thorin-Oakenpants** [comment]
OK, that sucked. There's an extra step .. set extensions.update.enabled = false before adding the theme, as it seems to update the theme as you install it - and then set it to true afterwards. It doesn't do this with the extension. I'm not entirely sure, because I could have sworn it was the older theme added, but the version numbers are so similar I may have made a mistake. Removing, restarting, and adding the old version theme when extensions.update.enabled = true simply gave me the latest up to date version.

When I looked at my test (timer is set for an hour), the theme was up to date but the extension wasn't (which lead me to the above paragraph), and then the extension updated while I was in there. Might set the timer for 10minutes and take a break.

**Comment by Thorin-Oakenpants** [comment]
I can confirm that the theme **IS UPDATED** by the daily background checks

If you want to confirm it: STR

-  `extensions.update.enabled` = false :exclamation: important as when true the theme installed would always be the latest one
-  `extensions.update.autoUpdateDefault` = true - so I know the background update fired
-  `lightweightThemes.update.enabled` = false
-  `extensions.update.interval` = 300 (5 minutes)
-  install 1 ext, 1 theme, both outdated versions
-  check versions installed are the old ones
-  `extensions.update.enabled` = true :exclamation: important to set this back for the test
- recheck versions are the old ones
- close
- open the test profile in 5+ minutes and give it a little time to fire. Took about 30 seconds and I was just waiting and saw the chrome "flicker", then checked the theme version, it was on the latest

I suspect the extension updates just include everything (and probably include search updates? which we could also check out)

**Comment by Thorin-Oakenpants** [comment]
@earthlng bump

**Comment by earthlng** [comment]
I think the thing is that most themes aren't really Lightweight Themes anymore. fe https://bugzilla.mozilla.org/1508777 mentions ...

> When AMO begins converting lightweight themes to packaged themes, users with recommended themes will end up with two copies of every converted lightweight theme.

They're apparently also in the process of removing LWTs completely, see [1469930](https://bugzilla.mozilla.org/show_bug.cgi?id=1469930) and [1525511](https://bugzilla.mozilla.org/show_bug.cgi?id=1525511) (opened 10 days ago). (and [Convert built-in LWTs to static themes](https://bugzilla.mozilla.org/show_bug.cgi?id=1525762) which was opened 10 days ago as well.)
I'm not sure but the only "lightweight" themes are seemingly just the 5 which are shipped with Firefox and only 3 of those are shown in the customize UI.

So yeah, the pref is probably mostly dead at this point but I'd still prefer to wait with removing it until they remove LWTs from Firefox entirely, including all their prefs, which looks like it should happen pretty soon.

**Comment by Thorin-Oakenpants** [comment]
- https://blog.mozilla.org/addons/2009/10/21/personas-now-on-amo/ - weeeeee .. personas back in 3.6, ahh the good old days
- https://blog.mozilla.org/addons/2018/07/12/upcoming-changes-for-themes/
- https://blog.mozilla.org/addons/2018/09/20/future-themes-here/

I'll put it back. I can understand someone may be using a persona they modified and don;t want it to update, but they do want extensions auto-updated. Pretty rare, but still. I guess we can wait for the pref to get removed .. in like 5 or 6 releases time

**Comment by Thorin-Oakenpants** [comment]
I still think it needs MOAR info that themes in 0301+0302 are not the same as 0307

**Comment by Thorin-Oakenpants** [comment]
bump

```js
/* 0307: disable auto updating of personas (lightweight themes / LWT)
 * LWT: not to be confused with those in 0301* + 0302*, which use the FF55+ Theme API
 * Mozilla plan to convert existing LWTs and remove persona support in the future, see [1]
 * [1] https://blog.mozilla.org/addons/2018/09/20/future-themes-here/  ***/
user_pref("lightweightThemes.update.enabled", false);
```

I think something like this removes all confusion. When the pref is deprecated we can trim that down or even just remove it from the js.

**Comment by earthlng** [comment]
looks great but why mention "personas" at all?
how about this?
```js
/* 0307: disable auto updating of lightweight themes (LWT)
 * LWT: not to be confused with themes mentioned in 0301* + 0302*, which use the FF55+ Theme API
 * Mozilla plan to convert existing LWTs and remove LWT support in the future, see [1]
 * [1] https://blog.mozilla.org/addons/2018/09/20/future-themes-here/  ***/
user_pref("lightweightThemes.update.enabled", false);
```

**Pull request merged**
