### PR TITLE
Use wget if curl is not available

### PR DESCRIPTION
**Pull request by ema-pe**
After the discussion on #447 I decided to send single pull requests improving the existent script instead of writing a new one.

This pull request add `wget` as fallback if `curl` is not installed. Why? Because `wget` is often preinstalled on most GNU/Linux distributions, and the end user doesn't need to install a new software for keeping updated the `user.js`.

If you use `wget` or `curl` the behaviour is the same, only the output can change a bit. For example with curl:

```

This script should be run from your Firefox profile directory.

Updating the user.js for Firefox profile:
/home/emanuele/Projects/ghacks-user.js

Your current user.js file for this profile will be backed up and the latest ghacks version from github will take its place.

If currently using the ghacks user.js, please compare versions:
  Available online: * version 61-alpha: You Can't Hurry Pants
  Currently using:  * version 61-alpha: You Can't Hurry Pants

If a user-overrides.js file exists in this profile, it will be appended to the user.js.

Continue Y/N? y


Your previous user.js file was backed up: userjs_backups/user.js.backup.2018-06-25_1749
downloading latest ghacks user.js file
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  130k  100  130k    0     0   177k      0 --:--:-- --:--:-- --:--:--  177k
ghacks user.js has been downloaded
```

And with `wget`:

```

This script should be run from your Firefox profile directory.

Updating the user.js for Firefox profile:
/home/emanuele/Projects/ghacks-user.js

Your current user.js file for this profile will be backed up and the latest ghacks version from github will take its place.

If currently using the ghacks user.js, please compare versions:
  Available online: * version 61-alpha: You Can't Hurry Pants
  Currently using:  * version 61-alpha: You Can't Hurry Pants

If a user-overrides.js file exists in this profile, it will be appended to the user.js.

Continue Y/N? y


Your previous user.js file was backed up: userjs_backups/user.js.backup.2018-06-25_1749
downloading latest ghacks user.js file
--2018-06-25 17:49:28--  https://raw.githubusercontent.com/ghacksuserjs/ghacks-user.js/master/user.js
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.112.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.112.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 133308 (130K) [text/plain]
Saving to: ‘user.js’

user.js                 100%[==============================>] 130.18K   528KB/s    in 0.2s    

2018-06-25 17:49:29 (528 KB/s) - ‘user.js’ saved [133308/133308]

ghacks user.js has been downloaded
```

### CODE REVIEW

**Comment by KOLANICH** [comment]
LOL. You may also want using `aria2c` if it is available ;) IMHO using multiple of very widespread downloaders is overkill, the most advanced should be used.

**Comment by earthlng** [comment]
> After the discussion on #447 I decided to send single pull requests improving the existent script instead of writing a new one.

thanks! :+1:

Looks good to me. If @overdodactyl gives the thumbs up I'll merge it

**Comment by ema-pe** [comment]
But `aria2c` is not preinstalled, while `curl` and `wget` are.

Also why should you use an advanced downloader if you need to download only a simple text file?

On 25 June 2018 19:11:48 CEST, KOLANICH <notifications@github.com> wrote:
>LOL. You may also want using `aria2c` if it is available ;) IMHO using
>multiple of very widespread downloaders is overkill, the most advanced
>should be used. 

-- 
Emanuele

Sent from my mobile, excuse my brevity.

**Comment by KOLANICH** [comment]
>But `aria2c` is not preinstalled, while `curl` and `wget` are. 

1 If curl were preinstalled, there would be no such a PR
2 aria2c is a must have anyway
3 for lulz, of course

**Comment by ema-pe** [comment]
Wget is preinstalled on most GNU/Linux distributions, while curl on Mac.

On 25 June 2018 19:39:18 CEST, KOLANICH <notifications@github.com> wrote:
>>But `aria2c` is not preinstalled, while `curl` and `wget` are. 
>
>1 If curl were preinstalled, there would be no such a PR
>2 aria2c is a must have anyway
>3 for lulz, of course

-- 
Emanuele

Sent from my mobile, excuse my brevity.

**Comment by KOLANICH** [comment]
Then it makes sense.

**Comment by earthlng** [comment]
Okay, I'm just gonna merge this because it doesn't look like @overdodactyl is checking his github very often.

@overdodactyl if you don't like these changes, feel free to create a new PR

**Comment by overdodactyl** [comment]
Changes look great, thanks @ema-pe  :) Sorry for being MIA, glad you went ahead with the merge!

**Pull request merged**
