### PR TITLE
update [SETTING] info

### PR DESCRIPTION
**Pull request by Thorin-Oakenpants**

### CODE REVIEW

**Comment by Thorin-Oakenpants** [comment]
> the setting can still exist but it's tied to the autofill system addon

I checked it in FF64 nilla profile, with the xpi present

**Comment by Thorin-Oakenpants** [comment]
`browser.crashReports.unsubmittedCheck.autoSubmit` => deprecated, will do separately (added it as an item in #533)

0517 - I put it back, wonder why it didn't show in 64 nilla

> 2701: Privacy & Security>Cookies and Site Data>**Accept/Block cookies and sit*e* data**

Why? It's exactly what I have it as, which is the combo box for "Type blocked"

**Comment by earthlng** [comment]
> Why? It's exactly what I have it as, which is the combo box for "Type blocked"

because the values are 0-4 and 0 is "Accept cookies and site data" which is not in "Type blocked".
But it doesn't really matter because the Content Blocking UI will be totally different again in FF65

**Comment by Thorin-Oakenpants** [comment]
will be changed again in 65. Figures! Anyway, lets not split hairs - I know some prefs are controlled/set by others, but if we went with yours, then it wouldn't match any UI setting. Will fire this thru then.

**Pull request merged**
