### PR TITLE
Update user-js.md

### PR DESCRIPTION
**Pull request by Thorin-Oakenpants**

### CODE REVIEW

**Comment by claustromaniac** [comment]
You apparently didn't notice that's Markdown inside HTML, and it's even in raw form. Wait, it's easier to *show* you what I mean...

**Comment by claustromaniac** [comment]
I merged both PR branches and pushed them to my fork, for previewing.
https://github.com/claustromaniac/ghacks-user.js/issues/new/choose

Click the `Get started` buttons there and see what you get.

**Comment by Thorin-Oakenpants** [comment]
I don't understand. The link syntax is the same as the readme.md. IDK.

**Comment by Thorin-Oakenpants** [comment]
If it can't be done then just close the PRs, canted be F'd anymore

**Comment by claustromaniac** [comment]
It can be done, but you'd have to get the text out of the `<!-- ... -->` tag (which is an HTML comment), but then:

1. the changes will render as links **only** in the preview
2. users will always have to clear the field to remove all that text before submitting their issues (or leave it there and end up with a cluttered post)

**Comment by claustromaniac** [comment]
You know what, on second thought, I'm liking the idea of getting that text ouf of the HTML tags, because that extra hoop that users have to go through to submit their issues (blanking out the field) is actually good. These guidelines are meant to target users that don't read much, so this works as a last line of defense against RTFM issues...

**Comment by Thorin-Oakenpants** [comment]
OK, I get it now, anything inside the `<!-- ` tags doesn't display.

But I don't follow what you mean in your last post? "I'm liking the idea of getting that text ouf of the HTML tags" <-- that bit? I was considering adding a single line of links above the `<!--` tag, e.g

[troubleshooting wiki](https://goats.com) | [changelogs](https://llamas.com) | [etc etc](https://alpacas.com)

Is that what you meant?

**Comment by Thorin-Oakenpants** [comment]
OK, so the links do work inside the tags? They didn't in your example. I am so confused now. I think I'll go back to `<country name withheld>` and do some more `<stuff>` and have another 10 days off

**Comment by claustromaniac** [comment]
Yes, I was talking about removing the tag itself (the `<!--` and `-->`) but I like that last idea of yours better.

**Comment by Thorin-Oakenpants** [comment]
and just change the instructions at the bottom to: "clear all of this when you're ready to type"

**Comment by Thorin-Oakenpants** [comment]
I'll let you do it all, while I go repack my bags and skiing gear

**Comment by claustromaniac** [comment]
Hmm.. they're gonna clear everything before posting anyway, so, if we removed the HTML comment tag, there's no need for markdown anymore, is there? Since, you know, github renders links as links.

Here is what I'm thinking (literal text that I would put in user-js.md):

---

We value feedback in general, but we value feedback from informed users more. There is no need for you to be an expert to participate (most of us aren't), but we hope that you at least understand our decisions before questioning them. We discuss all changes openly, and we do not make changes lightly. So, if you don't understand why we decided to add/remove/change a certain pref, search the repo. The answer is most certainly here.

If some change we made took you by surprise (in the wrong way), remember that keeping track of changes is your responsibility. Watch the repo, read the changelogs, compare releases as you update your copy of user.js, or use any other method you prefer.

Clear all of this when you're ready to type.

changelogs: https://github.com/ghacksuserjs/ghacks-user.js/issues?utf8=✓&q=is%3Aissue+label%3Achangelog
releases: https://github.com/ghacksuserjs/ghacks-user.js/releases

**Comment by claustromaniac** [comment]
I think that's better because it looks fine when you hit Preview (you get clickable links), the links appear after the most important text that users are meant to read, and it looks good in edit view.

**Comment by claustromaniac** [comment]
Or... we go back to the Markdown route, but without the HTML comment tag... which is what you wanted to do in the first place
```Markdown
We value feedback in general, but we value feedback from informed users more. There is no need for you to be an expert to participate (most of us aren't), but we hope that you at least understand our decisions before questioning them. We discuss all changes openly, and we do not make changes lightly. So, if you don't understand why we decided to add/remove/change a certain pref, search the repo. The answer is most certainly here.

If some change we made took you by surprise (in the wrong way), remember that keeping track of changes is your responsibility. Watch the repo, read the [changelogs](https://github.com/ghacksuserjs/ghacks-user.js/issues?utf8=✓&q=is%3Aissue+label%3Achangelog), compare [releases](https://github.com/ghacksuserjs/ghacks-user.js/releases) as you update your copy of user.js, or use any other method you prefer.

Clear all of this when you're ready to type.
```

**Comment by Thorin-Oakenpants** [comment]
OK, I'm just going to pull the trigger on these two PRs. If we hate it, I can always assign you to fix them up, revert them, re-design them, and triple-check them until I'm satisfied

**Comment by Thorin-Oakenpants** [comment]
Does the third one need changing as well?

**Comment by Thorin-Oakenpants** [comment]
it doesn't work: links are not linkified

**Comment by Thorin-Oakenpants** [comment]
doh: of course: it only shows in preview: ummm ... in that case this was a stupid idea on my part. I'll change em back a little later: I need to get away from all of this for a while

**Comment by Thorin-Oakenpants** [comment]
or we leave it as is, and when they preview, they get easy to click links: please advise

**Comment by Thorin-Oakenpants** [comment]
an illustration of :cat2: and myself working together

https://thechive.files.wordpress.com/2019/06/c23581fb2292c0d1028e74361cc75d59.gif

**Comment by claustromaniac** [comment]
LOL!

Yeah, I say we leave them like this. As for the other one... umm... We could make that one an actual template, actually. As in, really real template. With fields that users are meant to fill and so on. Dunno. TBH I was kinda lazy.

**Comment by Thorin-Oakenpants** [comment]
I think I'll wait until some raises an issue that says that the issues are not consistent

**Pull request merged**
