### PR TITLE
Update updater.sh

### PR DESCRIPTION
**Pull request by earthlng**
nicer diffs

### CODE REVIEW

**Comment by overdodactyl** [comment]
Code wise it looks good to me, but I won't have time to do much testing until later today.

Random side note: Given how much you've worked on this, you're more than welcome to move your name onto the "authors" line and include it in the "banner" as well.  We should also add @claustromaniac to the "contributors" line.

**Comment by earthlng** [comment]
if we want to support insanely long user-pref lines we can increase the sdiff width from 500 to 1000 or so, but other than that it should work pretty well (at least it did in my testing)

**Comment by claustromaniac** [comment]
I don't have a whole lot of experience with Bash. Is there any good reason not to use this in L320?
```bash
    diff=$(diff -B -d --suppress-common-lines -y -w $past_nocomments $current_nocomments)
```
It seems to have a much cleaner output than `sdiff`. Would using that help make this more readable? That being said, it works well for me as you wrote it.

> If you do not give `read` any arguments to use to hold the input (relying on the default variable `REPLY`), no whitespace is stripped and you can omit the modification to `IFS`.

Just FYI, changing `IFS` like this:
```bash
while IFS= read -r line; do
```
only applies to the scope of the `while` loop, meaning you don't need to save and restore IFS. Chepner's tip is cool though.

**Comment by overdodactyl** [comment]
I guess my biggest concern is how much the readability seems to depend on your window size and text editor.  I started out looking in Sublime full screen:

screen shot 2018-11-26 at 1 09 35 pm
  
For some reason it adds a ton of extra vertical space between entires can tell by the "map" on the right).

Switched to TextEdit and it was much better in full screen:

screen shot 2018-11-26 at 1 08 46 pm

But shrinking the window size a little made it more difficult to read:

screen shot 2018-11-26 at 3 37 15 pm

Next I checked out Xcode (full screen):

screen shot 2018-11-26 at 3 54 48 pm

**Comment by overdodactyl** [comment]
>It seems to have a much cleaner output than sdiff

It's better on my end, but Sublime and Xcode still doesn't seem to handle it great.

**Comment by earthlng** [comment]
> It seems to have a much cleaner output than sdiff

how so? we can use diff instead of sdiff. I only used sdiff because I somehow missed --suppress-common-lines in the man page :man_facepalming: But I get identical output from both.

As for what @overdodactyl posted, that seems to be a problem with either the code in Mac not working as expected OR your text-editor is set to wrap long lines, I'd guess.
Does diff (/sdiff) in Mac not use TABS to align left and right if you pass a long width?

**Comment by earthlng** [comment]
> IFS ... only applies to the scope of the while loop

thanks that's good to know. I was wondering about that but didn't care to look it up because that other guys solution works perfect here and is shorter

**Comment by earthlng** [comment]
> diff=$(diff -B -d --suppress-common-lines -y -w $past_nocomments $current_nocomments)

not sure how good `-d` works but we can definitely add it.
`--suppress-common-lines -y` can replace `sdiff -s`
`-B` is redundant (isn't it?) because we're diffing pre-stripped files but we can add it anyway.
IDK about using -w though. What exactly does "ignore all white space" mean? Is "hello world" the same as "helloworld" then? Probably not but there's also -b and that's why I'm confused

**Comment by claustromaniac** [comment]
I meant to say that using `diff` instead of `sdiff` might help make *the script* more readable (sorry about that). On my end `diff` outputs a lot less spaces, so I don't need to edit the output to read it somewhat comfortably. If that is not consistent across different OSes, I guess it doesn't matter anyway.

**Comment by earthlng** [comment]
@overdodactyl add an `echo $leasttabs` after the while and if that's in the 50-60 range the problem can only be in `sed -E ...`. I can't help much more because I don't have a mac and the code works in Linux

**Comment by earthlng** [comment]
@claustromaniac wait what? How the hell is
`diff=$(diff -y -W 1000 -B -d  -w --suppress-common-lines $past_nocomments $current_nocomments)`
more readable than
`diff=$(sdiff -s -w 1000 -B -d $past_nocomments $current_nocomments)` ? :smile:

**Comment by earthlng** [comment]
> On my end diff outputs a lot less spaces, so I don't need to edit the output to be able to read it somewhat comfortably. If that is not consistent across different OSes, I guess it doesn't matter anyway.

so I guess it doesn't work on your end either then. It should look like this https://github.com/ghacksuserjs/ghacks-user.js/pull/555#issuecomment-441727759

**Comment by claustromaniac** [comment]
> `-B` is redundant (isn't it?)

Indeed.

> wait what? How the hell is ... more readable than ...

Sure, that line is not more readable that way, but if `diff` outputs just enough spaces to separate the two columns reasonably, maybe you wouldn't need some of the other lines below that one. That's how ***THE SCRIPT*** would be more readable.

As for your other questions... I have a whole 10 minutes of empirical knowledge + shitty documentation. I'll see if I can find something to reply to those accurately.

**Comment by claustromaniac** [comment]
Dude you're misunderstanding everything I said. Ugh. 

Try just 
```shell
diff -B -d --suppress-common-lines -y -w "file1" "file2"``` > temp.txt
vs
```
sdiff -s -w 1000 -B -d "file1" "file2" > temp.txt
```
in the TERMINAL, and see the difference.

**Comment by earthlng** [comment]
> you wouldn't need some of the other lines below that one

Oh now I see what you mean. Yeah sure we can do that but then it either truncates the lines or there's unnecessary space in between. I found using a fixed width is not ideal and that's what the lines below are for but apparently it only works on my system

**Comment by claustromaniac** [comment]
>  I found using a fixed width is not ideal and that's what the lines below are for but apparently it only works on my system

I wouldn't be so sure about that. :sweat_smile: Both dactyl and I said what you wrote works fine to begin with! I just suggested a *possible* way to make the script somewhat shorter ***maybe***. That's all, really.

**Comment by overdodactyl** [comment]
I think using `-t`(`--expand-tabs`) in `diff` is the magic solution for me.  

It looks like `diff` uses x number of tabs, then equals out the spacing via spaces.  Each text editor of mine was treating tabs as a different number of spaces, so it didn't line up properly.

**Comment by earthlng** [comment]
I feel you misunderstood my stupidly placed smiley. It wasn't meant in an offensive way, like laughing at you, at all! I just didn't get that you meant also getting read of the lines below to make THE SCRIPT more readable. Sorry about that

but yeah if we don't care about truncated lines then we can just add `-d --suppress-common-lines -y` and remove all the extra garbage. I'm totally fine with that.
I just wanted to see if I can simulate "auto-width" diffs instead of fixed width, that's all.

**Comment by earthlng** [comment]
> Each text editor of mine was treating tabs as a different number of spaces, so it didn't line up properly.

oh okay so it's an editor issue and you'd have that problem whenever you use `-y` without `-t`.
We could work around that by letting `diff` use spaces instead of TABS but it wouldn't be quite as easy to simulate auto-width as it was with TABS.

**Comment by claustromaniac** [comment]
> I feel you misunderstood my stupidly placed smiley. It wasn't meant in an offensive way, like laughing at you, at all!

Don't you worry, I know you're not such a jerk :laughing: Failing to make myself clear is frustrating, that's all. In fact, I wanted to apologize more for the confusion, but I abstained from doing so because the conversation already got needlessly long (by my fault :crying_cat_face:).

**Comment by earthlng** [comment]
but looking at your screenshots that doesn't seem to be the only problem.
fe in the Xcode pic, IF the code was working as expected, there should only be one tab and a few spaces after `... crashReports.unsubmittedCheck.enabled", false);` but there are clearly more

**Comment by earthlng** [comment]
how many tabs between aaa and bbb are left after this? `echo -e "aaa\t\t\t\t\t\tbbb" | sed -E 's/\t{4}//1'`

**Comment by overdodactyl** [comment]
>how many tabs between aaa and bbb are left after this?

It looks like 5 full tabs, 1 partial tab (?), and 0 spaces:

screen shot 2018-11-26 at 5 52 51 pm

**Comment by overdodactyl** [comment]
>but looking at your screenshots that doesn't seem to be the only problem

Ya, the `sdiff` version seemed to have additional problems as well.

**Comment by earthlng** [comment]
how many with this? `TAB=$"\t"; echo -e "tab\t\t\t\t\t\ttab" | sed -E 's/'${TAB}'{4}//1'`

**Comment by overdodactyl** [comment]
Same thing there

**Comment by overdodactyl** [comment]
>Default on my linux VM is 130

**Comment by earthlng** [comment]
I'll close this PR and if you want (potentially truncated or very wide) side-by-side diffs at all you can just change that one line and add the options you want.

Sorry for wasting your time guys

**Comment by claustromaniac** [comment]
I'm really sorry I can't participate right now, because I have to do some stuff, but I couldn't help it: I have to say this...

> hallelujah!!

We should totally find a place to gather physically and register this repo as a church, à la [Our Lady of Perpetual Exemption.](https://en.wikipedia.org/wiki/Our_Lady_of_Perpetual_Exemption)

Who is with me?!!!

**Comment by overdodactyl** [comment]
Not a waste at all @earthlng! I was thinking this would be a good way to go as well, sorry I wasn't of more help this PR!

**Comment by Thorin-Oakenpants** [comment]
If we're a registered church... can we [Canonize](https://github.com/ghacksuserjs/ghacks-user.js/issues/535#issuecomment-441651697) shit?

**Comment by claustromaniac** [comment]
Well, I just thought it would be fun to be legally allowed to ask for money and reply with letters like [this](https://c1.staticflickr.com/6/5814/24087531116_9919c9b24c_c.jpg). Then again, we may have to end up [closing](http://www.ourladyofperpetualexemption.com/) anyway.

That won't stop me from treating the `user.js` as our holy book from now though!!!

**Comment by claustromaniac** [comment]
> If we're a registered church... can we [Canonize](https://github.com/ghacksuserjs/ghacks-user.js/issues/535#issuecomment-441651697) shit?

Good prefs that end up deprecated would be good candidates for canonization IMO :angel:

**Comment by Thorin-Oakenpants** [comment]
OMG ... :angel: is now my new fav emoji

**Comment by earthlng** [comment]
Well you have my approval if you want to start something :)

we could probably even get an endorsement from Trump because he thinks *everything* is GREAT.
Although a Trump endorsement could be counter-productive ... unless ... we can also get a Clinton endorsement! somebody got some spare couple hundred K's to "donate" to the Clinton Foundation?
GOD BLESS THE USA FOR PAY-2-PLAY!! hallelujah! USA-USA-USA

**Comment by earthlng** [comment]
too soon?

**Pull request closed without merging**
